config:
  telegramBotToken:
    secretRef:
      name: telegram-bot-secret
      key: token
  telegramApiUrl:
    value: "https://tapi.bale.ai/"
  zaiApiKey:
    secretRef:
      name: zai-secret
      key: api-key
  zaiBaseUrl:
    value: "https://ai.snapp.tech/v1"
  zaiModel:
    value: "glm-5"

extraEnvFrom:
  - secretRef:
      name: my-extra-secret
